#!/bin/bash -l
#SBATCH --job-name=heat_diffusion
#SBATCH --time=0:3:0
#SBATCH --partition=a100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --mem-per-cpu=4G
#SBATCH --gres=gpu:2
#SBATCH --account=rmittal3_gpu
export CUDA_VISIBLE_DEVICES=0,1
# run your job

module load gcc/9.3.0
module load cuda/11.8.0
module load openmpi/4.1.6
module load pmix/5.0.1 


export LD_LIBRARY_PATH=/data/apps/extern/spack_on/gcc/9.3.0/pmix/5.0.1-kwqmucdwnzfpjiwj3x3j36yukklykdj4/lib:$LD_LIBRARY_PATH
##nsys profile -o profile_report ./matmul_multigpu > out.log
srun -n 2 ./2gpu_bicg >  out.log
##nvidia-smi topo -m > out.log
